### ISSUE TITLE
Create zend-router

### ISSUE THREAD

**Issue by bakura10** [zendframework/zend-mvc#1]
Hi :),

Could anyone create a zend-router repository please? That would allow to backport @DASPRiD Dash router into it!

Thanks!

**Comment by Maks3w** [comment]
I think this issue can be closed

**Comment by weierophinney** [comment]
I want to move it to a separate repo prior to v3, so, no, let's keep this
open.

**Comment by weierophinney** [comment]
zend-router now exists: [zend-router](https://zendframework.github.io/zend-router/).

As for Dash, that can/should be offered as a parallel offering, and I've already spoken to @DASPRiD about it.
