### ISSUE TITLE
parsing json can throw RuntimeException in AbstractRestfulController

### ISSUE THREAD

**Issue by svycka** [zendframework/zend-mvc#100]
in AbstractRestfulController here https://github.com/zendframework/zend-mvc/blob/ba5c1e124ba07965bfadc1abe2373431025e73db/src/Controller/AbstractRestfulController.php#L453 and https://github.com/zendframework/zend-mvc/blob/ba5c1e124ba07965bfadc1abe2373431025e73db/src/Controller/AbstractRestfulController.php#L576 can throw not catched exceptions leading to 500 response when header `Content-Type: application/json` and body is not valid json.

Is this bug or not? if not how can I workaround this? The only way to silent this I see is to override these methods or https://github.com/zendframework/zend-mvc/blob/ba5c1e124ba07965bfadc1abe2373431025e73db/src/Controller/AbstractRestfulController.php#L311 but I am not sure I want this.

**Comment by svycka** [comment]
To be more clear. In this situation I would like to not throw exception but validate the input and return with proper error message instead of this error. But this happens before I can do any validation in the controller.

**Comment by weierophinney** [comment]
@svycka If you want to validate, override the method:

``` php
public function processPostData(Request $request)
{
    try {
        return parent::processPostData($request);
    } catch (\Exception $e) {
        // do something with the exception
    }
}
```

Alternately, make the method override a no-op, and manually handle it.

**Comment by svycka** [comment]
@weierophinney so I should do it like this?

``` php
class TestController extends AbstractRestfulController
{
    public function create($data)
    {
        // data validation
    }

    public function update($id, $data)
    {
        // data validation
    }

    public function processPostData(Request $request)
    {
        try {
            return parent::processPostData($request);
        } catch (\Exception $e) {
            // first validation
        }
    }

    protected function processBodyContent($request)
    {
        try {
            return parent::processBodyContent($request);
        } catch (\Exception $e) {
            // second validation
        }
    }
}
```

but how many user does this? this is not documented and at least I didn't know this until sow errors in logs.

if this is desired behavior then feel free to close this.

**Comment by weierophinney** [comment]
@svycka At this point, it's the intended behavior; the `AbstractRestfulController` provides a convenience layer for the 80% use case.

Another option is to do the validation _earlier_, which is what Apigility does. In zf-content-negotiation, we have a route listener (on negative priority; runs once we know what route was matched) that does the body parameter parsing. This allows us to return a 400 response when we have JSON decoding errors.
