### ISSUE TITLE
Deprecation Warning Not appearing on ViewHelper

### ISSUE THREAD

**Issue by axelcho** [zendframework/zend-mvc#106]
I was reviewing a code submitted by another developer. He was creating a new ViewHelper, and he implemented ServiceLocatorAwareInterface to load some services in the ViewHelper. The code actually located service using ServiceLocator. 

I have been following #87 and I expected a deprecation warning. I did not see anything.

As for our code, we refactored it using factories. Just wondering about the missing deprecation warning.

**Comment by weierophinney** [comment]
View helpers are governed by the zend-view `HelperPluginManager`. Interestingly, that plugin manager does not register an initializer for injecting the `ServiceLocatorAwareInterface` instances!

However, the `Zend\View\Helper\Navigation\PluginManager` _does_, as the navigation helpers need access to navigation containers, which are registered as services at the application level. This initializer should only ever be injected _if you are using navigation helpers_; if not, it will not be.

The **tl;dr**: We likely need to address this in zend-view, but I'm not entirely sure how we'll do so and still keep the navigation helpers working. Regardless, I'd point your developer to [my blog post on the subject](https://mwop.net/blog/2016-04-26-on-locators.html) and recommend they do not rely on that feature!
