### ISSUE TITLE
Call to undefined method Zend\Mvc\View\Http\ViewManager::getExceptionStrategy()

### ISSUE THREAD

**Issue by markushausammann** [zendframework/zend-mvc#109]
I have this code:

```
$exceptionStrategy = $event->getApplication()->getServiceManager()->get('ViewManager')->getExceptionStrategy();
$exceptionStrategy->detach($this->eventManager);
```

Which started triggering an Error:

> Call to undefined method Zend\Mvc\View\Http\ViewManager::getExceptionStrategy()

because `getExceptionStrategy()` is obviously missing. How to do the same things now?

**Comment by weierophinney** [comment]
It's in the service manager now as the service `HttpExceptionStrategy`:

``` php
$exceptionStrategy = $event->getApplication()->getServiceManager()->get('HttpExceptionStrategy');
```

This means you can also supply your own listener aggregate to attach as an exception strategy by overriding that service.

**Comment by markushausammann** [comment]
Thank you for your quick help Matthew.

What we did already before was this:

```
$exceptionStrategy = (PHP_SAPI == 'cli') ? (new SentryConsoleStrategy()) : (new SentryHttpStrategy());
$exceptionStrategy->attach($this->eventManager);
```

... and it still seems to work the same way. I just needed to replace that one line of code you provided.
