### ISSUE TITLE
`Zend\Mvc\MvcEvent#getRouteMatch()` should be annotated `RouteMatchInterface|null`

### ISSUE THREAD

**Issue by Ocramius** [zendframework/zend-mvc#11]

**Comment by samsonasik** [comment]
I can't find <code>RouteMatchInterface</code> interface under  <code>src/</code>

**Comment by weierophinney** [comment]
@Ocramius Agreed with @samsonasik - there is no `RouteMatchInterface`. I'm assuming the change you want is adding the `null|` aspect to the return annotation?

**Comment by Ocramius** [comment]
> I'm assuming the change you want is adding the null| aspect to the return annotation

Right

**Comment by samsonasik** [comment]
@Ocramius @weierophinney I've created PR #18 for this ;)
