### ISSUE TITLE
composer/dependency: zendframework/zend-console should be moved to "require"

### ISSUE THREAD

**Issue by akomm** [zendframework/zend-mvc#13]
Zend\Mvc\Service\ViewManagerFactory depends on Zend\Console\Console:
https://github.com/zendframework/zend-mvc/blob/master/src/Service/ViewManagerFactory.php#L12

On production this causes a "class X not found" fatal error.

zendframework/zend-console should be moved to "require"

_edit_

I think I see now the problem. There are to many different "sub-components" in mvc, like in other zendframework/*-packages, which depends on something. If you would require them all, because theoretical some classes in the package require it, you would most probably require the whole zendframework. Is that the reason, why all the packages are in require-dev & suggestion?

**Comment by gianarb** [comment]
Hi @akomm 

This is not an issue.. Zend\Console for a lot of community members is "suggested" because resolve only one feature of Zend\Mvc.. :) 

This problem was discussed a lot of time :)
http://gianarb.it/blog/the-price-of-modularity/

**Comment by weierophinney** [comment]
You can use both `Zend\Mvc\Application` and `Zend\Mvc\Router`, as well as controllers, completely separately from the default service definitions used within the skeleton application; as such, it's considered an optional suggestion.

> If you would require them all, because theoretical some classes in the package require it, you would most probably require the whole zendframework. Is that the reason, why all the packages are in require-dev & suggestion?

Correct; it allows fine-grained usage. The application developer determines how much or how little of the package they want to use.
