### ISSUE TITLE
Error In launching Nginad

### ISSUE THREAD

**Issue by chiduke2001** [zendframework/zend-mvc#130]
Hi,
I installed the nginad server but it has errors and cant work.
there's some issue with the MySQL Database tables. The system is throwing error with every login attempt, you can try any login info at http://68.233.227.45/auth/authenticate.

Please confirm if the Database Scheme here: https://nginad.atlassian.net/wiki/display/NGIN/Installing+NginAd+MySQL+Database+Server+RDB# is the valid database to use. or suggest another.

 I am getting the error below: "The supplied parameters to DbTable failed to produce a valid sql statement, please check table and column names for validity." 

Thanks
[nginad error.docx](https://github.com/zendframework/zend-mvc/files/218042/nginad.error.docx)

**Comment by weierophinney** [comment]
Please report your issue to NginAd, as the problem is with their usage of zend-authentication and/or your own configuration of the database for interfacing with their product.

**Comment by chiduke2001** [comment]
Hi,

NginAd is not responding.

I wonder the low class customer service they have.

Please is there anything you can do to help?

Thanks
