### ISSUE TITLE
ModuleRouteListener not attached by default

### ISSUE THREAD

**Issue by sophpie** [zendframework/zend-mvc#136]
I haven't see anything about that, and I am not sure, but it seems that since 2.7 ModuleRouteListener is not attached by default to EVENT_ROUTE. Is it the result of my misunderstanding, or a regression ?

**Comment by weierophinney** [comment]
We've never attached it by default within zend-mvc, only within the skeleton application:
- https://github.com/zendframework/ZendSkeletonApplication/blob/57c1011bb356546d0b4b8b6b3b26bd5e870acbcf/module/Application/Module.php#L20-L21

As such, check and see if you introduced a change into that file in your application.
