### ISSUE TITLE
rawurlencode function in Regex router

### ISSUE THREAD

**Issue by albrin** [zendframework/zend-mvc#154]
I doing an online store on ZF2.

I want to make URL as SEO-friendly and user friendly.

For example,

```
/catalog/sectionA/sectionB/
/catalog/sectionA/sectionB/sectionC/
/catalog/sectionA/sectionB/sectionC/sectionD/sectionN/
```

Nesting categories can be any and is generated dynamically.

My routes

```
'catalog_product' => [
    'type' => 'regex',
    'options' => [
        'regex' => '/catalog/(?<section>[a-zA-Z0-9_-]+)/(?<product>[a-zA-Z0-9_-]+).html$',
        'defaults' => [
            'controller' => 'AlbrinCatalog\Controller\Catalog',
            'action' => 'view'
        ],
        'spec' => '/catalog/%section%/%product%.html'
    ]
],
```

In view
`<a href="{{ url('catalog_product', {'section': product.section_full_path, 'product': product.code}) }}">`

I get
`/catalog/sectionA%2FsectionB/`
instead of
`/catalog/sectionA/sectionB/`

Because in zend-mvc\src\Router\Http\Regex rawurlencode($value)

```
    public function assemble(array $params = [], array $options = [])
    {
        $url                   = $this->spec;
        $mergedParams          = array_merge($this->defaults, $params);
        $this->assembledParams = [];

        foreach ($mergedParams as $key => $value) {
            $spec = '%' . $key . '%';

            if (strpos($url, $spec) !== false) {
                $url = str_replace($spec, rawurlencode($value), $url);

                $this->assembledParams[] = $key;
            }
        }

        return $url;
    }
```

What can I do?

**Comment by albrin** [comment]
Does anyone think that something about this?
I do not know what to do in this situation, use Regex router and url() plugin.

I really need help with this.

I had never seen such an implementation.

As I understand it for the solution of this issue will need to make changes to the code of the component?

**Comment by michalbundyra** [comment]
I think the simplest solution will be to write own class - own Route type, and use it in routing.
You just need implement interface [`RouteInterface`](https://github.com/zendframework/zend-router/blob/master/src/Http/RouteInterface.php). Always you can see how [`Segment`](https://github.com/zendframework/zend-router/blob/master/src/Http/Segment.php) and/or [`Regex`](https://github.com/zendframework/zend-router/blob/master/src/Http/Regex.php) are implemented and it shouldn't be a problem to write exactly what you need.

Please take a look also at [documentation: HTTP Route Types](http://zendframework.github.io/zend-router/routing/#http-route-types).
