### ISSUE TITLE
Why zend-mvc must use PHP5.6 or higher in V3?

### ISSUE THREAD

**Issue by Moln** [zendframework/zend-mvc#156]
I saw `composer.json` require `"php": "^5.6 || ^7.0"`.
I'm trying to change `^5.5 || ^7.0` , and run application successful.

**Comment by kokspflanze** [comment]
PHP 5.5 will be outdated on 10 Jul 2016 http://php.net/supported-versions.php, i think that will be the reason for this change. Also it is now possible to use 5.6 features.

https://github.com/zendframework/zend-mvc/pull/128

**Comment by weierophinney** [comment]
Yes, PHP 5.6 is the target version at this point due to the fact that 5.5 will no longer have active support a month from now. We will be aggressively updating our minimum PHP version going forward, in order to promote an ecosystem that keeps their PHP versions secure.

**Comment by Moln** [comment]
:+1:  Thanks everybody!
