### ISSUE TITLE
Added $data parameter to delete() in AbstractRestfulController

### ISSUE THREAD

**Issue by GeeH** [zendframework/zend-mvc#172]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

---

Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/7416
User: @ahoppen
Created On: 2015-04-04T11:06:18Z
Updated At: 2015-11-06T23:57:35Z
Body
Now that the $data parameter has been added to `deleteList` in #7255, it would be inconsistent to not provide it to `delete`. 
Data for a delete request can be useful for example to validate a user’s password before deleting him.

---

**Comment by samsonasik** [comment]
already fixed at https://github.com/zendframework/zendframework/pull/7255 , close-able
