### ISSUE TITLE
[ZF3] zend-serializer is required

### ISSUE THREAD

**Issue by matbech** [zendframework/zend-mvc#185]
In Controller\LazyControllerAbstractFacatory.php there is a reference to zend-serializer:
use Zend\Serializer\AdapterPluginManager as SerializerAdapterManager;

Therefore the zend-serializer is required in the composer.json dependencies or at minimum in the 'suggest' section.

Another option would be to remove the SerializerAdapterManager alias:
        SerializerAdapterManager::class => 'SerializerAdapterManager',
or replace the SerializerAdapterManager::class with the actual class name string.

**Comment by weierophinney** [comment]
The lazy controller factory is opt-in. At most, we need to add a suggestion to the composer definition. Would you like to create a pull request with this change?

**Comment by matbech** [comment]
LazyControllerAbstractFacatory uses additional aliases for which further suggestions (zend-console, zend-log, etc) would be required:
use Zend\Console\Adapter\AdapterInterface as ConsoleAdapterInterface;
use Zend\Log\FilterPluginManager as LogFilterManager;

```
    LogProcessorManager::class      => 'LogProcessorManager',
    LogWriterManager::class         => 'LogWriterManager',
```

So I'm not sure whether adding them all to the 'suggest' section is an elegant solution?
