### ISSUE TITLE
Is some way to setting every module use custom layout and error template?

### ISSUE THREAD

**Issue by leolicai** [zendframework/zend-mvc#189]
The is a very important problem for me.
The site have some modules, eg: home site, blog, shop. etc.
Every module have themself artist to design the ui.
So, Is a simple way to config the module themself layout setting?
I don't like set the layout in the controller, just want every controller focus the logic.
I'm try edit the module.config.php, at the view_manager section use some key to setting the module's layout. 
But all config will be merged. Only last module config is actived.
So, some man can give a suggestion?
Thanks!

**Comment by froschdesign** [comment]
@leolicai 
You can use the "[EdpModuleLayouts](https://github.com/EvanDotPro/EdpModuleLayouts)" module or you write your own listener.

**Comment by leolicai** [comment]
@froschdesign 
I'm use ZF3, You code can't run, the $e->getApplication(); is empty.
and, the config was merged. all controller extends the AbstractController 
All module will ben use one layout. 
btw, someboy has the question about custom error page.
how to fix it?
Thanks man.

**Comment by drakulitka** [comment]
It would be a good example to Twig template!!

**Comment by Zebercet** [comment]
@leolicai it's onBootstrap event and $e is MvcEvent. `$e->getApplication() `can not be null at there.

**Comment by ghost** [comment]
@leolicai Did you find a solution for this?

**Comment by froschdesign** [comment]
@burrellramone 
Please have a look at the documentation of zend-view: "[Cookbook - Setting module-specific Layouts](https://docs.zendframework.com/zend-view/cookbook/setting-module-specific-layouts/)"

**Comment by ghost** [comment]
Why do I need 100+ lines of code to do something that ought to be basic in a framework that is suppose to be module based? I'll try it nevertheless and see if it works.

**Comment by froschdesign** [comment]
@burrellramone 
We are open for constructive criticism and for proposals of all kinds.

The Zend Framework is a community driven project and everyone can contribute.
If you miss something or found an inadequacy, then we look forward to any assistance. You can create a feature request or create a pull request to add the desired function.

Thanks in advance!

**Comment by MatthiasKuehneEllerhold** [comment]
The idea of modules here is that you have your layout and view scripts and extend them with extra module that add functionality.
So its more like that the basic layout is thought to be coming from one module and all other modules just append functionality (without any views) or generic views that you can include.
