### ISSUE TITLE
Redirect plugin refresh with query params

### ISSUE THREAD

**Issue by semihs** [zendframework/zend-mvc#190]
i have tried $this->redirect()->refresh(); in my controller
it is refreshing but excluded query params

sample path: /tr/dashboard/advert/category/1/translate?language_id=1

it is removing language_id

same problem with toRoute method, need to do as following:

```
$this->redirect()->toRoute(null, [], ['query' => ['language_id' => 1]], true);
```

**Comment by Xerkus** [comment]
Neither controller plugins or url view helper reuse query parameters, you need to pass them explicitly:
`$this->redirect()->toRoute(null, [], ['query' => $request->getQuery()->toArray()], true);`
