### ISSUE TITLE
[Question] Can we enable piped style middleware router for ZF MVC just like in Expressive?

### ISSUE THREAD

**Issue by gabbydgab** [zendframework/zend-mvc#196]
I've tried mapping routes to middleware just like in the [docs](https://docs.zendframework.com/zend-mvc/middleware/#mapping-routes-to-middleware) but as of the moment it can only invoke one middleware action.

Is there a way we can integrate the [piped style middleware router](https://docs.zendframework.com/zend-expressive/cookbook/route-specific-pipeline/#what-about-pipeline-middleware-configuration) like in Zend Expressive? Or this feature is for the Router?

**Comment by Ocramius** [comment]
Can probably produce a middleware pipe from the factory responsible of dispatching a certain middleware. Needs some fiddling, but you'd implement a middleware that wraps a set of middlewares, basically.

**Comment by gabbydgab** [comment]
how sad T_T

still hoping for this to happen soon :)
