### ISSUE TITLE
Replace private methods with protected

### ISSUE THREAD

**Issue by anton-kotik** [zendframework/zend-mvc#201]
[github.com/zendframework/zend-mvc/search?q=private](https://github.com/zendframework/zend-mvc/search?l=php&q=private&utf8=%E2%9C%93)

Using private methods makes it difficult to override their classes.

**Comment by weierophinney** [comment]
We will evaluate these on a case-by-case basis, based on reported need.

Making them private allows us to refactor internals without worrying about impact on end-users; a strong case needs to be made for us to expose any private methods as protected, as doing so creates a maintenance cost for the project.

**Comment by anton-kotik** [comment]
@weierophinney, I tried to override HttpExceptionStrategyFactory to use my custom ExceptionStrategy.

This code doesn't work as expected because `HttpExceptionStrategyFactory::__invoke()` [doesn't use](https://github.com/zendframework/zend-mvc/blob/master/src/Service/HttpExceptionStrategyFactory.php#L27-L29) `$name` argument:

``` php
namespace Application\Mvc\Service;

use Application\Mvc\MyCustomExceptionStrategy;
use Zend\Mvc\Service\HttpExceptionStrategyFactory as BaseFactory;

class HttpExceptionStrategyFactory extends BaseFactory
{
    public function createService(ServiceLocatorInterface $container)
    {
        return $this($container, MyCustomExceptionStrategy::class);
    }
}
```

So I had to override `__invoke()` method too and I can't use [private methods](https://github.com/zendframework/zend-mvc/blob/master/src/Service/HttpExceptionStrategyFactory.php#L30-L33).

Other zend-mvc strategies have the same problem.
