### ISSUE TITLE
ServiceManager's build method question.

### ISSUE THREAD

**Issue by digitalfu** [zendframework/zend-mvc#203]
Given the decision to stop encouraging the use of the [Service Locator in controller/arbitrary contexts](https://github.com/zendframework/zend-mvc/issues/137), what are the valid use cases for the `build` method that it provides? 

The [docs](https://zendframework.github.io/zend-servicemanager/configuring-the-service-manager/#passing-config-to-a-factorydelegator) talks about context, but I have no idea how to pass that context in if the locator isn't being passed into one itself, I guess that platform context would be available but that is nothing that we can't do with a standard factory that has access to the config service.

Is there an acceptable way to pass (for instance) a user context into a factory for model creation?

**Comment by weierophinney** [comment]
@digitalfu `build()` is used for the following:
- To build the initial instance of a service.
- To create new instances of a service marked as _not shared_
- Within plugin managers, which often mark services as unshared, and/or allow passing instantiation options when creating the service; in this latter case, passing options implicitly indicates an unshared service.

The context is only passed when calling `build()` directly, or using a plugin manager instance.
