### ISSUE TITLE
EventManagerAwareInitializer issue

### ISSUE THREAD

**Issue by thomasvargiu** [zendframework/zend-mvc#205]
The [EventManagerAwareInitializer](https://github.com/zendframework/zend-mvc/blob/e263600c6c8d4cb4d69a3b610dc1bb34860aad16/src/Service/ServiceManagerConfig.php#L83-L106) causes an issue when someone uses the instance event manager before the initializer.

I was upgrading a project from zend-eventmanager v2 to zend-eventmanager v3, and to attach listeners to services' EventManager I use to do it in an `DelegatorFactory`:

``` php

namespace ModuleA\Service;

use Interop\Container\ContainerInterface;
use ModuleB\Listener\MyListener;
use Zend\ServiceManager\DelegatorFactoryInterface;
use Zend\ServiceManager\ServiceLocatorInterface;

class LockServiceDelegator implements DelegatorFactoryInterface
{

    public function __invoke(ContainerInterface $container, $requestedName, callable $callback, array $options = null)
    {
        $service = call_user_func($callback);
        $listener = $container->get(MyListener::class);
        $listener->attach($service->getEventManager());
        return $service;
    }

    public function createDelegatorWithName(ServiceLocatorInterface $serviceLocator, $name, $requestedName, $callback)
    {
        return $this($serviceLocator, $requestedName, $callback);
    }
}
```

`zend-mvc` and its initializer aren't compatible with `zend-eventmanager` ^3.0, because it overrides the instance EventManager (without `SharedServiceManager`) after delegators.

How to resolve:
- ~~Don't use the `EventManagerAwareInterface` but just `EventsCapableInterface` (the right way)~~
- Inject a composed Event Manager with its Shared Manager in the instance factory

I think this should be mentioned in the migration guide.

**Comment by thomasvargiu** [comment]
Edit:
I think the best way is to inject a composed Event Manager with its Shared Manager in the instance factory when creating a service

**Comment by Xerkus** [comment]
You are right, initializer is checking presence of shared event manager to detect if it was set in factory.

I am going to close this as won't fix. In next major version EventManager initializer will be removed.
