### ISSUE TITLE
Another Uncaught TypeError

### ISSUE THREAD

**Issue by ghost** [zendframework/zend-mvc#212]
PHP Fatal error:  Uncaught TypeError: Argument 4 passed to Zend\\Mvc\\DispatchListener::marshalBadControllerEvent() must be an instance of Exception, instance of ParseError given

**Comment by Ocramius** [comment]
You are most likely using an old version of `zendframework/zend-mvc`, since the hint was removed, and isn't there in version 3.0.4: https://github.com/zendframework/zend-mvc/blob/3d198677428c0d0839ef30331d35b54dd8a093bb/src/DispatchListener.php#L219
