### ISSUE TITLE
Unable to resolve service "Zend\Db\Adapter\AdapterInterface" to a factory

### ISSUE THREAD

**Issue by forethoughtde** [zendframework/zend-mvc#213]
I am following through the GETTING STARTED WITH ZEND FRAMEWORK tutorial document. I come to a point where I get the following error message. 

> /var/www/vendor/zendframework/zend-servicemanager/src/ServiceManager.php:681
> 
> Unable to resolve service "Zend\Db\Adapter\AdapterInterface" to a factory; are you certain you provided it during configuration?

Can anyone explain me what is going on in my code?

**Comment by froschdesign** [comment]
@forethoughtde 
Have you added `zend-db` as module in your "config/modules.config.php"?

```php
return [
    'Zend\Db',
    /* ... */
],
```

https://docs.zendframework.com/tutorials/getting-started/database-and-models/#using-servicemanager-to-configure-the-table-gateway-and-inject-into-the-albumtable

**Comment by forethoughtde** [comment]
Spot on. It works now. Thanks"
