### ISSUE TITLE
Zend\Mvc\Router\RoutePluginManager does not exist in Zend Framework

### ISSUE THREAD

**Issue by andreidiaconescu** [zendframework/zend-mvc#215]
In the documentation it is written:
"

> A TreeRouteStack will consist of the following configuration:
> 
>     A base "route", which describes the base match needed, the root of the tree.
>     An optional route_plugins, which is a configured Zend\Mvc\Router\RoutePluginManager that can lazy-load routes.
> .........................
> 
> $routePlugins = new Zend\Mvc\Router\RoutePluginManager();
> $plugins = [
>     'hostname' => 'Zend\Mvc\Router\Http\Hostname',
>     'literal'  => 'Zend\Mvc\Router\Http\Literal',
>     'part'     => 'Zend\Mvc\Router\Http\Part',
>     'regex'    => 'Zend\Mvc\Router\Http\Regex',
>     'scheme'   => 'Zend\Mvc\Router\Http\Scheme',
>     'segment'  => 'Zend\Mvc\Router\Http\Segment',
>     'wildcard' => 'Zend\Mvc\Router\Http\Wildcard',
>     'query'    => 'Zend\Mvc\Router\Http\Query',
>     'method'   => 'Zend\Mvc\Router\Http\Method',
> ];
> foreach ($plugins as $name => $class) {
>     $routePlugins->setInvokableClass($name, $class);
> }
> 

"

But the class Zend\Mvc\Router\RoutePluginManager does not exist.

Can you please let us know how to use the plugins for routes ?

**Comment by froschdesign** [comment]
The router was transferred to its own component: [`zend-router`](https://github.com/zendframework/zend-router)

The documentation is outdated on this place. Thanks for reporting!
