### ISSUE TITLE
Controller manager assuming method exists.

### ISSUE THREAD

**Issue by bweston92** [zendframework/zend-mvc#23]
Controller manager assuming `getServiceLocator` exists on an interface where it is not a required method.

https://github.com/zendframework/zend-mvc/blob/master/src/Controller/ControllerManager.php#L63
https://github.com/zendframework/zend-servicemanager/blob/master/src/ServiceLocatorInterface.php

Thank god for loose typing :D

**Comment by weierophinney** [comment]
The ControllerManager is a plugin manager, and is assumed to be working in the context of an application, where it will be injected with the application service manager instance. 

This will change for ZF3, as plugin managers will be injected with the application service manager at instantiation, and will set that instance as the "context" to be used when passed to factories.

As such, I'm closing this issue; the usage currently is "as designed," but we recognize the problems with the design, and have a planned solution in the next major version.
