### ISSUE TITLE
Problem on DispatchListener with a controller abstract factory

### ISSUE THREAD

**Issue by Ppito** [zendframework/zend-mvc#238]
Hello,

I develop a module of error handler to integrate whoops in Zend Framework 3 ([Ppito/zf3-whoops](https://github.com/Ppito/zf3-whoops)), and because of a bug issue was open to me, we found a limitation on distach with a controller abstract factory.

The problem is, when a syntax error is generated with abstract factory configuration, the application crashes when it's tried to create the controller.
Can you move the test of creation on the try/catch below ? Otherwise the error cannot be caught and a blank page appears.

Like that : 
```php
try {
    // Query abstract controllers, too!
    if (! $controllerManager->has($controllerName)) {
        $return = $this->marshalControllerNotFoundEvent($application::ERROR_CONTROLLER_NOT_FOUND, $controllerName, $e, $application);
        return $this->complete($return, $e);
    }

    $controller = $controllerManager->get($controllerName);
} catch (Exception\InvalidControllerException $exception) {
    $return = $this->marshalControllerNotFoundEvent($application::ERROR_CONTROLLER_INVALID, $controllerName, $e, $application, $exception);
    return $this->complete($return, $e);
} catch (InvalidServiceException $exception) {
    $return = $this->marshalControllerNotFoundEvent($application::ERROR_CONTROLLER_INVALID, $controllerName, $e, $application, $exception);
    return $this->complete($return, $e);
} catch (\Throwable $exception) {
    $return = $this->marshalBadControllerEvent($controllerName, $e, $application, $exception);
    return $this->complete($return, $e);
} catch (\Exception $exception) {  // @TODO clean up once PHP 7 requirement is enforced
    $return = $this->marshalBadControllerEvent($controllerName, $e, $application, $exception);
    return $this->complete($return, $e);
}
```

**Comment by Ocramius** [comment]
This is up to your abstract factory to handle: `has` operations should be silent. If your abstract factory performs unsafe operations such as reflection, code discovery, etc, then `AbstractFactory#canCreate` needs to be designed in a safe way.

Closing as `invalid`, since `ContainerInterface#has()` does indeed not expect exceptions to be thrown, and the code using `has` shouldn't either.

**Comment by bitwombat** [comment]
If there's a syntax error in a controller, the `class_exists` call in  `\Zend\Mvc\Controller\LazyControllerAbstractFactory::canCreate` throws an exception.

**Comment by Ocramius** [comment]
Yes, and that is up to the maintainer of that abstract factory to fix that,
if relevant.

**Comment by Ppito** [comment]
yes, but it's not an exception we need to catch, it's a php error. And it's this php error that will be nice to be catch with `Throwable` (only in php 7, I know).

**Comment by Ocramius** [comment]
No, that mentality will just lead you to having every layer of everything
being wrapped in a try-catch. Fix your factory to be compliant with the
silent signature.

**Comment by Ppito** [comment]
yes, yes, I know that. Ok thanks anyway.

**Comment by bitwombat** [comment]
@Ocramius you say "your factory", but this factory is part of \Zend\Mvc.  Do I just need to make a separate, more specific issue?

**Comment by Ocramius** [comment]
Yes, or a PR
