### ISSUE TITLE
AbstractConsoleController

### ISSUE THREAD

**Issue by datashuttle** [zendframework/zend-mvc#239]
No longer at this namespace

**Comment by froschdesign** [comment]
Is this a question, bug report or something else?!

Maybe I am wrong, but see: https://github.com/zendframework/zend-mvc-console

**Comment by datashuttle** [comment]
It's a statement. The docs make reference to the wrong namespace for the AbstractConsoleController.

**Comment by froschdesign** [comment]
That's the missing statement: 

> The docs make reference to the wrong namespace for the AbstractConsoleController.

Thanks for reporting!

**Comment by datashuttle** [comment]
Yes, sorry for not clarifying.

**Comment by samsonasik** [comment]
@datashuttle I've created PR #240 for it.
