### ISSUE TITLE
Zend\Mvc\Controller\AbstractController returning Zend\Http\Request but Zend\Stdlib\RequestInterface in comments

### ISSUE THREAD

**Issue by SevenbitsIt** [zendframework/zend-mvc#241]
use Zend\Http\Request as HttpRequest;
use Zend\Stdlib\RequestInterface as Request;

This causes the methode getRequest()  state that it returns a   RequestInterface but it really returns  a 
HttpRequest. This only effects Documentation but fix is simple to only change comments to full path:

`
/**
     * Get request object
     *
     * @return \Zend\Http\Request
     */
    public function getRequest()`

**Comment by froschdesign** [comment]
Sorry for the late response.

Nothing wrong, because:

* `Zend\Http\Request` implements the interface `Zend\Stdlib\RequestInterface`
* the `AbstractController` handles also non-http requests, like CLI
