### ISSUE TITLE
zend-console required in 2.7.12

### ISSUE THREAD

**Issue by Koopzington** [zendframework/zend-mvc#242]
I'm still running projects on zend-mvc 2.7.* and tried to remove zend-console from one of them.
After doing so i was presented an error telling me that Zend\Console\Console was not found.
[The RequestFactory apparenty needs zend-console](https://github.com/zendframework/zend-mvc/blob/release-2.7.12/src/Service/RequestFactory.php#L48) while in 3.0 everything console related got removed.
[Since zend-console is only in require-dev](https://github.com/zendframework/zend-mvc/blob/release-2.7/composer.json#L28) we should maybe consider moving it to 'require' for the 2.7 branch... or just do nothing at all and tell people to upgrade to 3.0 already ;)

**Comment by samsonasik** [comment]
I've created PR #245 to add zend-console to require for 2.7

**Comment by weierophinney** [comment]
Fixed with #245.
