### ISSUE TITLE
Router plugin constructor backwards-incompatible due to AbstractPluginFactory

### ISSUE THREAD

**Issue by nathanjosiah** [zendframework/zend-mvc#244]
I upgraded from ZF 2.5.1 to ZF 2.5.3. I have a custom router plugin that extends the Http\Segment plugin and I have attached a delegator to it in the ServiceManager. My extended plugin doesn't override the constructor but I'm seeing that when the plugin is created in the ServiceManager via the delegator callback, all the arguments are being passed as an array into the first param.

I don't understand what I need to update to make this happy again. The delegator behavior seems unusual.

**Zend segment router plugin debug**
```php
namespace Zend\Mvc\Router\Http;
class Segment implements RouteInterface {
    public function __construct($route, array $constraints = [], array $defaults = []) {
        // $this is an instance of MyPlugin
        // $route is an array [route=>...,constraints=>...defaults=>...]

        $this->defaults = $defaults;
        $this->parts    = $this->parseRouteDefinition($route);
        $this->regex    = $this->buildRegex($this->parts, $constraints);
    }
    // etc
}
```

## My code

**The plugin**
```php
namespace MyNamespace\Router\Plugin;
use Zend\Mvc\Router\Http\Segment;
class MyPlugin extends Segment { 
    // My setters/getters
}
```

**The delegator**

```php
namespace MyNamespace\Router\Plugin;
use Zend\ServiceManager\DelegatorFactoryInterface;
use Zend\ServiceManager\ServiceLocatorInterface;

class MyPluginServiceDelegator implements DelegatorFactoryInterface {
    public function createDelegatorWithName(ServiceLocatorInterface $routePluginManager, $name, $requestedName, $callback) {
        $plugin = $callback(); // Error happens here
        // Set custom stuff
        return $plugin;
    }
}
```

### Context code

**The default listener**

>  **Note** These default listener classes in the form of factories are the only userland code that executes before the router config is merged into the router. This means that dynamically added routes, or routes with custom plugins must be added through this fairly hacky way by way of a default listener that is obtained through a ServiceManager factory. Even then, it is only made possible because the factory interface requires a ServiceLocator to be injected. **There may be a better way to do this in 2.5.3 but as of 2.5.1 there was not.**

```php
namespace MyNamespace;

use Zend\EventManager\ListenerAggregateInterface;
use Zend\EventManager\EventManagerInterface;
use Zend\ServiceManager\FactoryInterface;

class DefaultListenerServiceFactory implements ListenerAggregateInterface,FactoryInterface {
    public function createService(\Zend\ServiceManager\ServiceLocatorInterface $serviceLocator) {
        $router = $serviceLocator->get('Router');
        $route_plugin_manager = $router->getRoutePluginManager();
        $route_plugin_manager->setInvokableClass('MyPlugin','MyNamespace\Router\Plugin\MyPlugin');
        $route_plugin_manager->addDelegator('MyPlugin','MyNamespace\Router\Plugin\MyPluginServiceDelegator');
        $router->addRoute('myroute',[
            'type' => 'MyPlugin',
            'options' => [
                // etc
            ]
        ],1000);
        return $this;
    }

    // We don't actually care about the events. We only use this listener/factory to be able to add the route plugin dynamically
    public function detach(EventManagerInterface $events) {}
    public function attach(EventManagerInterface $events) {}
}
```

**The module config**

```php
return [
    'listeners' => [
        'MyNamespace\DefaultListener'
    ],
    'service_manager' => [
        'factories' => [
             'MyNamespace\DefaultListener' => MyNamespace\DefaultListenerServiceFactory::class,
        ],
    ],
    // etc
];
```

**Comment by Ocramius** [comment]
@nathanjosiah I assume there's no factory for `MyPlugin`?

**Comment by nathanjosiah** [comment]
@Ocramius Correct, the listener is adding it as an invokable class `$route_plugin_manager->setInvokableClass('MyPlugin','MyNamespace\Router\Plugin\MyPlugin');`

**Comment by Ocramius** [comment]
Could you try with an invokable factory? Just tossing ideas around, as this
would need to be reproduced in a test to be debugged

**Comment by nathanjosiah** [comment]
I will work on creating an isolated test case repo.

**Comment by nathanjosiah** [comment]
@Ocramius Either using an invokable factory or just by setting an alias to the FQCN of the plugin fixes the issue. 

I haven't read through the new invokable factory-related code but I was unaware that there were other changes made. I have a test repo but I don't want to waste your/my time if you already know what the issue is. I can try and debug further to find a root cause if you'd like.

**Comment by Ocramius** [comment]
>  I don't want to waste your/my time if you already know what the issue is

I actually don't, but invokables have been deprecated in favor of invokable factories, so maybe we broke something in the compatibility layer that translates invokable keys into factory keys.

**Comment by nathanjosiah** [comment]
@Ocramius I've isolated the issue to a single file outside of an MVC app:

```php
namespace {
    include __DIR__ . '/vendor/autoload.php';
}
namespace MyNamespace {
    class MyPlugin extends \Zend\Mvc\Router\Http\Segment {
        public function __construct() {
            echo '<pre>';
            var_dump(func_get_args());
            echo '</pre>';
            exit;
        }
    }
}
namespace {
    $route_plugin_manager = new \Zend\Mvc\Router\RoutePluginManager(new Zend\ServiceManager\ServiceManager());
    $route_plugin_manager->setInvokableClass('MyPlugin','MyNamespace\MyPlugin');
    //$route_plugin_manager->setFactory('MyNamespace\MyPlugin',\Zend\ServiceManager\Factory\InvokableFactory::class);
    //$route_plugin_manager->setAlias('MyPlugin','MyNamespace\MyPlugin');
    $route_plugin_manager->get('MyPlugin',[
        'route' => '/test'
    ]);
}
```

After debugging, the problem with the Invokable is the [AbstractPluginManager:254](https://github.com/zendframework/zend-servicemanager/blob/release-2.7.8/src/AbstractPluginManager.php#L254) is passing the creationOptions as a constructor argument. 

The InvokableFactory actually doesn't work because it's doing the [same thing](https://github.com/zendframework/zend-servicemanager/blob/release-2.7.8/src/Factory/InvokableFactory.php#L62) as the AbstractPluginManager.

The reason setting an alias works (in this case) is the ServiceManager finds the RouteInvokableFactory which is also correctly [passing the arguments](https://github.com/zendframework/zend-mvc/blob/release-2.7.12/src/Router/RouteInvokableFactory.php#L122) to the constructor.


I'm not sure what the proper fix for this would be though. I'm happy to make a PR but I don't know which direction you would like to take with this.

**Comment by nathanjosiah** [comment]
@Ocramius Apologies if you read my email already from my last comment, I updated it to say the InvokableFactory doesn't work because it does the same thing as the AbstractPluginManager.

**Comment by nathanjosiah** [comment]
@Ocramius I've been thinking about this and based on the existence of the RouteInvokableFactory, I think the intended behavior and the migration path is to use custom invokable factories to handle plugin creations. Is this a correct assumption?

**Comment by Ocramius** [comment]
> I think the intended behavior and the migration path is to use custom invokable factories to handle plugin creations. Is this a correct assumption?

I really don't know/don't know how to help further here.

The route plugins were quite a mess in the past, due to [this horrible interfaced static constructor](https://github.com/zendframework/zend-router/blob/f75dee88dde6b2cebc123a225be0c2b17015ffdf/src/RouteInterface.php#L24-L30) (tip: don't interface constructors for non-data objects!).

I don't know how the code was migrated, but I assume that a custom factory is needed at all times when instantiating custom route types.
