### ISSUE TITLE
What's better?

### ISSUE THREAD

**Issue by dimon-smith** [zendframework/zend-mvc#25]
What's better?

```
$smConfig = isset($configuration['service_manager']) ? $configuration['service_manager'] : [];
$serviceManager = new ServiceManager(new Service\ServiceManagerConfig($smConfig));
```

OR

```
$smConfig = &$configuration['service_manager'] ;
$serviceManager = new ServiceManager(new Service\ServiceManagerConfig((array)$smConfig));
```

**Comment by manuakasam** [comment]
I'd go with the first one.

PHP7 would then further allow for `$smConfig =
$configuration['service_manager'] ?? []`

dimon-smith notifications@github.com schrieb am So., 6. Sep. 2015 um
19:43 Uhr:

**Comment by dimon-smith** [comment]
@manuakasam 
mmm... But zf3 must be compatible with php 5 ...

**Comment by Ocramius** [comment]
@dimon-smith you were asking about an approach, not about what zendframework's approach should be.
