### ISSUE TITLE
MiddlewareListener namespace update for new version of Interop\Http\MiddlewareInterface

### ISSUE THREAD

**Issue by yurivecchi** [zendframework/zend-mvc#256]
Hi!

As http-interop/http=middleware updated their code to comply with PSR-15 changes, MiddlewareListener doesn't got updated to follow the new namespace, only necessary change is the import from:

use Interop\Http\ServerMiddleware\MiddlewareInterface;

to:

use Interop\Http\Server\MiddlewareInterface;

and all keeps working.

I can do the PR or you will wait for the PSR to be approved?

**Comment by froschdesign** [comment]
`Interop\Http\Server\MiddlewareInterface` is deprecated in favor of [PSR-15](https://github.com/php-fig/http-server-middleware).

See also: #259 – open for comments!
