### ISSUE TITLE
ServiceManager section in documentation is need to update

### ISSUE THREAD

**Issue by Zebercet** [zendframework/zend-mvc#265]
Almost every link on [this page](http://zendframework.github.io/zend-mvc/services/#servicemanager) is broken. They are goes to 2.4 documentation. Here some sample:

https://framework.zend.com/manual/2.4/en/zend.form.elements.intro.html
https://framework.zend.com/manual/2.4/en/zend.paginator.usage.paginating.adapters.html
https://framework.zend.com/manual/2.4/en/zend.validator.set.html

**Comment by froschdesign** [comment]
The wrong links are:

* http://framework.zend.com/manual/current/en/zend.form.elements.intro.html
* http://framework.zend.com/manual/current/en/zend.paginator.usage.paginating.adapters.html
* http://framework.zend.com/manual/current/en/zend.validator.set.html
* http://framework.zend.com/manual/current/en/zend.db.adapter.html
* http://framework.zend.com/manual/current/en/zend.form.quick-start.factory.html

In this file: https://github.com/zendframework/zend-mvc/blob/master/docs/book/services.md

**Comment by Xerkus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Use as many boards as you want!](https://trello.com/c/jPwnrgEk/13-use-as-many-boards-as-you-want)
