### ISSUE TITLE
provide interfaces for onDispatch() and onBootstrap()

### ISSUE THREAD

**Issue by BigMichi1** [zendframework/zend-mvc#267]
is it possible to include one or more interfaces for 
```php 
public onDispatch(MvcEvent $event)
```
and 
```php
public onBootstrap(MvcEvent $event) 
```
This would make it clearer why these methods exists in an applications Module.php and so there is a possibility to include some default documentation

**Comment by froschdesign** [comment]
> ```php
> public onBootstrap(MvcEvent $event) 
> ```

See at the Module Manager: https://docs.zendframework.com/zend-modulemanager/module-manager/#onbootstraplistener

**Comment by Xerkus** [comment]
Interfaces are provided by Module Manager, which provides those features in modules.
