### ISSUE TITLE
Parent route passes it's action option to children

### ISSUE THREAD

**Issue by Zebercet** [zendframework/zend-mvc#269]
I don't know if it's an issue or feature but here how is it happens.

```
'router' => [
            'routes' => [
                'api' => [
                    'type' => Segment::class,
                    'options' => [
                        'route'    => '/api[/]',
                        'defaults' => [
                            'controller' => Controller\Api\HelloAction::class,
                            'action' => 'process'
                        ],
                    ],
                    'child_routes' => [
                        'type' => Segment::class,
                        'options' => [
                            'route' => 'books[/:id][/]',
                            'defaults' => [
                                'controller' => Controller\Api\BooksRestfullController::class,
                            ]
                        ]
                    ]
                ],
            ],
        ],
```

As you can see i fotgot to add "may_terminate" to "api" route so "ApiHelloAction" won't answer but "BooksRestfullController" -which's extends from AbstractRestfullController"- also won't work as RestfullController.  "onDispatch" method [here](https://github.com/zendframework/zend-mvc/blob/e67b7fd4b3c64e45613b679f8cbbd3fa19d9cf1d/src/Controller/AbstractRestfulController.php#L324) got "process" as action which's "api" route's action. If i add "may_terminate" option to "api" route everything is works as "expected"

Update: "may_terminate" does not make everything works well for child routes. "action" is "process" for children controllers. So if you map action of a restful controller's, it's mean you have to map child route's action too. Maybe it's how router works but documentation does not mention it.

**Comment by Xerkus** [comment]
Parent route parameters are combined with those of child routes.

Please direct your question to our support channels:
- For real-time questions, use our [Slack](https://zendframework-slack.herokuapp.com)
- For detailed questions (e.g., those requiring examples) use our [forums](https://discourse.zendframework.com/c/questions/components)

**Comment by Zebercet** [comment]
Yes, this can be the working principle of router but it broke's AbstractRestfulController. If you map a controller's action, you have to map child controller's action too..
