### ISSUE TITLE
http-interop/http-middleware abandoned

### ISSUE THREAD

**Issue by mishbah** [zendframework/zend-mvc#275]
If you check this site https://github.com/http-interop/http-middleware
You'll see message

**Note: This repository is deprecated and no longer updated. Please refer to [http-interop/http-server-handler](https://github.com/http-interop/http-server-handler) and [http-interop/http-server-middleware](https://github.com/http-interop/http-server-middleware) instead.**

**Comment by froschdesign** [comment]
See: #259

**Comment by froschdesign** [comment]
Duplicate of #256
