### ISSUE TITLE
zend-mvc requires i18n with forms

### ISSUE THREAD

**Issue by Zebercet** [zendframework/zend-mvc#276]
I don't know if it's mvc's or form's error but here's situation;

composer:
```
"require": {
    "zendframework/zend-mvc": "^3.1",
    "zendframework/zend-navigation": "^2.8",
    "zendframework/zend-form": "^2.11"
  },
```

versions in composer.lock file

> zendframework/zend-mvc - 3.1.1
> zendframework/zend-navigation - 2.8.2
> zendframework/zend-form - 2.11.0

Form is simple;

```
public function init()
{
     $this
           ->add([
               'type'       => Element\Text::class,
               'name'       => SettingsInterface::SITE_TITLE,
               'options'    => [
                   'label' => 'Title',
               ],
               'attributes' => [
                   'maxlength'             => 150,
                   'data-plugin-maxlength' => true,
               ],
       ]);
}
```
and view file;

```
echo $this->form($form);
```

and log file;

`Class 'Zend\\I18n\\View\\Helper\\AbstractTranslatorHelper' not found in /etc/source-code/vendor/zendframework/zend-form/src/View/Helper/AbstractHelper.php on line 21`

**Comment by froschdesign** [comment]
Replace `zendframework/zend-form` with `zendframework/zend-mvc-form` in your Composer file and all is fine.
