### ISSUE TITLE
Segment route issue

### ISSUE THREAD

**Issue by mikemix** [zendframework/zend-mvc#28]
Consider this route:

``` php
            'home' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/[page-:page.html]',
                    'constraints' => [
                        'page' => '\d+',
                    ],
                    'defaults' => [
                        'controller' => 'App\Controller\Front\Index',
                        'action'     => 'index',
                    ],
                ],
            ],
```

When trying to generate an url for this route with `$router->assemble(['page' => 10], ['name' => 'home')` instead of `/page-10.html` I get `/`.

The router obviously does not like my dot there. Is this an expected behavior?

**Comment by weierophinney** [comment]
@DASPRiD — can you take a look at this, please?

**Comment by DASPRiD** [comment]
@mikemix try this:

`route' => '/[page-:page:.html]',`

**Comment by mikemix** [comment]
Will do. I've never seen route param written down this way in the docs.
