### ISSUE TITLE
Exception not visible when render.error events happen

### ISSUE THREAD

**Issue by FabianRahm** [zendframework/zend-mvc#289]
### Code to reproduce the issue

In a view template, eg. index.phtml we might have some wrong code during development like the following function call where $unsetVar has never been declared or passed to the view template. 

`<?php echo $unsetVar->method(); ?>`

PHP Environment:
```
error_reporting(E_ALL);
ini_set("display_errors", 1);
```

Module: zend-mvc v. 3.1.1

### Expected results

I would like to see the exception on screen with both the actual PHP error happening and the stack trace.
Error: Call to a member function method() on null in index.phtml:1
Stack trace:
#0 /...app/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(506): include()
...

### Actual results

An exception is thrown on screen but the PHP error and the stack trace are not visible.

I can workaround this by attaching an event listener during onBootstrap to listen for render.error events happening but I'd rather find a solution to see the exception without a special listener.

**Comment by samsonasik** [comment]
I created [`ErrorHeroModule`](https://github.com/samsonasik/ErrorHeroModule) for that which you can enable `display_errors` in configuration and it will shows like this:

![screen shot 2018-07-08 at 6 04 57 am](https://user-images.githubusercontent.com/459648/42415333-00b2e80a-8275-11e8-8707-91d235d763e6.png)

**Comment by Xerkus** [comment]
Non fatal errors generate exceptions in PHP7 and intercepted by framework.
Please check that `$config['view_manager']['display_exceptions']` is set to `true` if you use ZendSkeletonApplication.
If value is true, please check that your application error templates include check for `Throwable` or `Error`:
https://github.com/zendframework/ZendSkeletonApplication/blob/7581703d5979c090b74905c5c7f5e7f2c527c980/module/Application/view/error/index.phtml#L4-L7
```php
<?php if (! empty($this->display_exceptions)) : ?>
    <?php if (isset($this->exception)
        && ($this->exception instanceof \Exception || $this->exception instanceof \Error)) : ?>
<hr/>
```

**Comment by FabianRahm** [comment]
Thank you @Xerkus - I had the first config flag already set to true but didn't get the error template update where the second OR '\Error' check was added. 

Works like a charm.
