### ISSUE TITLE
Argument 1 passed to Zend\Mvc\Service\ModuleManagerFactory::__invoke must be integer, object given

### ISSUE THREAD

**Issue by Yunfeng1u** [zendframework/zend-mvc#300]
It's fine on my pc, but I got a http 500 error when I deployed on my centOS 7. 

```
2019/01/15 17:03:26 [error] 26448#0: *5069938 FastCGI sent in stderr: "PHP message: PHP Catchable fatal error:  Argument 1 passed to Zend\Mvc\Service\ModuleManagerFactory::__invoke must be integer, object given in /usr/share/nginx/interface/vendor/zendframework/zend-mvc/src/Service/ModuleManagerFactory.php on line 37
PHP message: PHP Stack trace:
PHP message: PHP   1. {main}() /usr/share/nginx/interface/public/index.php:0
PHP message: PHP   2. Zend\Mvc\Application::init() /usr/share/nginx/interface/public/index.php:41
PHP message: PHP   3. Zend\ServiceManager\ServiceManager->get() /usr/share/nginx/interface/vendor/zendframework/zend-mvc/src/Application.php:264
PHP message: PHP   4. Zend\ServiceManager\ServiceManager->doCreate() /usr/share/nginx/interface/vendor/zendframework/zend-servicemanager/src/ServiceManager.php:200
PHP message: PHP   5. Zend\Mvc\Service\ModuleManagerFactory->__invoke() 
```

I traced the source code and it seems fine.
```
public function __invoke(ContainerInterface $container, $name, array $options = null)
```
None of these arguments require an integer type.
 
So I wonder if my env goes wrong. Here is part of my `composer.json` file: 
```
"require": {
        "php": "^5.6",
        "zendframework/zend-component-installer": "^1.0 || ^0.7 || ^1.0.0-dev@dev",
        "zendframework/zend-mvc": "^3.0.1",
        "zfcampus/zf-development-mode": "^3.0",
        "zendframework/zend-cache": "^2.7.1",
        "zendframework/zend-json": "^3.0",
        "zendframework/zend-mvc-i18n": "^1.0",
        "zendframework/zend-mvc-plugins": "^1.0.1",
        "zendframework/zend-psr7bridge": "^0.2.2",
        "zendframework/zend-servicemanager-di": "^1.0",
        "ramsey/uuid": "^3.7",
        "firebase/php-jwt": "^5.0",
        "aliyuncs/oss-sdk-php": "^2.3",
        "spipu/html2pdf": "^5.1",
        "php-curl-class/php-curl-class": "^8.0",
        "zendframework/zend-permissions-rbac": "^2.6",
        "apache/log4php": "^2.3",
        "zircote/swagger-php": "2.0.13",
        "predis/predis": "^1.1",
        "stripe/stripe-php": "^6.12",
        "joshcam/mysqli-database-class": "dev-master",
        "solarium/solarium": "3.8.1",
        "hashids/hashids": "2.0.4"
    }
```

**Comment by weierophinney** [comment]
This looks like you may have a configuration error. Can you dump the "service_manager" values from any configuration files you have, please? Look for them in:

- `config/autoload/*.php`
- `modules/*/config/*.config.php`

I suspect that one of these is malformed.

Additionally, I recommend you run `composer update`, as the most recent version of zend-mvc is 3.1.1.

**Comment by Yunfeng1u** [comment]
@weierophinney 
I have searched all this config files and found nothing about `service_manager ` value. Then I run `composer create-project zendframework/skeleton-application
` to create a sample application, same error occurs. I guess something like php-extensions is missing.

**Comment by Yunfeng1u** [comment]
I made a same request in unit-test by running `./vendor/bin/phpunit`, it went well!
Then I change the file `/vendor/zendframework/zend-mvc/src/Service/ModuleManagerFactory.php`:
```
public function __invoke(ContainerInterface $container, $name, array $options = null)
    {
        var_dump(123);
        exit();
        $configuration    = $container->get('ApplicationConfig');
        $listenerOptions  = new ListenerOptions($configuration['module_listener_options']);
        $defaultListeners = new DefaultListenerAggregate($listenerOptions);
        $serviceListener  = $container->get('ServiceListener');
        ...
    }
```
And it print `int(123)`, so it did call `ModuleManagerFactory::__invoke()`

Two way:
* Different between unit-test and index.php
* Different between command line and http request

**Comment by Yunfeng1u** [comment]
Found that there is 2 php on my server. One is installed with php-fpm, called `php56`, another comes with system. 

Run `php ./vendor/bin/phpunit ...`, ok.
Run `php56 ./vendor/bin/phpunit ...`, the same error occurs.

So I will try to compare two of these php.

**Comment by Yunfeng1u** [comment]
Finally, it's the php strict mode cause the "error", disable the php-strict extension.
My `40-strict.ini` file:
```
; Enable strict extension module
; zend_extension=strict.so
```

**Comment by weierophinney** [comment]
@Yunfeng1u I've never even _heard_ of that extension; do you have any details on where it comes from?

(I know `declare(strict_mode=1)` exists, and we use it in our libraries that have a minimum PHP version of 7 or greater; however, that directive is per-file, and would not affect this. I've also heard of [autostrict](https://github.com/krakjoe/autostrict), which essentially auto-sets that directive in every file, but that extension is named `autostrict.so`. And there is no `strict` extension in the [PHP sources](https://github.com/php/php-src/tree/master/ext). I have not been able to find the extension despite a number of different searches, so I'm _really_ curious about it!)

**Comment by Yunfeng1u** [comment]
@weierophinney 
I don't know how it came from either. But you can run `yum install php-strict` to install it. There are my installed extensions: 
```
yum list installed | grep strict
Repository nodesource is listed more than once in the configuration
Repository nodesource-source is listed more than once in the configuration
php-pecl-strict.x86_64                0.4.1-2.el7.remi.5.6           @remi-php56
php56-php-pecl-strict.x86_64          0.4.1-2.el7.remi               @remi
```
However, it seems like a Zend Extension instead of PHP Extension.  [Click for more information](https://centos.pkgs.org/7/remi-x86_64/php56-php-pecl-strict-0.4.1-1.el7.remi.x86_64.rpm.html). 

```
php -m
...
[Zend Modules]
XCache Cacher
XCache Coverager
XCache Optimizer
Xdebug
Zend OPcache
the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured)
uopz
```
It was under the `[Zend Modules]` before I disable the extension.

**Comment by weierophinney** [comment]
Found it: https://pecl.php.net/package/strict

I'm surprised it even runs on PHP 7, to be honest. It was essentially a way to add strict mode to PHP 5 versions, and there's no need for it in PHP 7; based on what it was reporting, it looks like the extension does not perfectly mimic what PHP 7 does, either.

Considering its age (last commit was 5 years ago), and release status (beta), I'd recommend not using it in stable PHP releases at this point.
