### ISSUE TITLE
Error to load controller after update to zend 2.6.0dev

### ISSUE THREAD

**Issue by voltan** [zendframework/zend-mvc#317]
Hello

We have custom CMS by zf2, I try update zend version to version 2.6.0dev, But after that I have `A 404 error occurred` 

```

A 404 error occurred

Page not found.





Additional information:

The requested controller could not be mapped to an existing controller class.

Controller:
    system-index-index (resolves to invalid controller class or alias: index) 


```

any important change happened to version 2.5.3 and 2.7.15?
can you help me to understand the problem?

**Comment by Ocramius** [comment]
Hey there,

It looks like something you'd have to debug (write an integration test) and then bisect: not something maintainers can help you with until you isolated the root cause.
