### ISSUE TITLE
Compatibility with PHP 7.3?

### ISSUE THREAD

**Issue by herbergt** [zendframework/zend-mvc#318]
I cannot find anywhere on the internet if the components of Zend Framework 3, including the zend-mvc are compatible with php 7.3. 

Does anyone can help me with this information? 

I want to upgrade the version of PHP from 7.2 to 7.3

**Comment by michalbundyra** [comment]
@herbergt Yes, ZF MVC is compatible with PHP 7.3 :) I just noted that we are not running tests on PHP 7.3 so it should be fixed. We are also compatible with PHP 7.4 - expect two modules as far as I know - zend-db and zend-mail (in very edge cases). We are working on these to have all modules compatible also with PHP 7.4!

**Comment by herbergt** [comment]
Good to know that @michalbundyra . Thank you for your help.
