### ISSUE TITLE
Fatal error when not installing specific components

### ISSUE THREAD

**Issue by DASPRiD** [zendframework/zend-mvc#35]
While cleaning up a project's composer.json today, I noticed that Zend\Mvc is going throw fatal errors when a few specific components are not installed, namely these:
- zend-console
- zend-log
- zend-serializer

On a side-node, Zend\ModuleManager has the same problem, throwing a fatal error when zend-config is missing.

All those packages only appear in the suggest section, but apparently they should be in require when fatal errors are thrown otherwise.

**Comment by weierophinney** [comment]
Is this still true on the latest versions?

**Comment by weierophinney** [comment]
Closing, as this is addressed with the v3 work (now completed as of #128).
