### ISSUE TITLE
Is there a way of telling if a route exists?

### ISSUE THREAD

**Issue by akond** [zendframework/zend-mvc#41]
Let's say I have several languages on my site: EN,DE,ES.
One page may be accessible through language-specific  urls: /en/page, /de/seite, /es/pagina
A SEO-guy may add/change/remove any language specific route as he pleases.
If there is no language specific route, a fall-back route should be used.

$router->assemble ('lang/route') does not always work. 
It throws if there is no route, and I'm reluctant to use try/catch.

On the other hand $router->getRoute ('lang') returns  \Zend\Mvc\Router\Http\Part, which is not collaborative either.

What should I do?

**Comment by waltertamboer** [comment]
You might enjoy [@juriansluiman's library](https://github.com/juriansluiman/SlmLocale) ([URI path docs](https://github.com/juriansluiman/SlmLocale/blob/master/docs/2.Strategies.md#path-segment-of-uri)).

Further more it's possible to translate parts of routes:
https://github.com/zendframework/zend-router/blob/master/src/Http/TranslatorAwareTreeRouteStack.php
