### ISSUE TITLE
Composer Requirements

### ISSUE THREAD

**Issue by waltertamboer** [zendframework/zend-mvc#45]
When installing zend-mvc via composer, one will get an error when creating an application:
`Fatal error: Class 'Zend\ModuleManager\Listener\ListenerOptions' not found`

I see the that zend-modulemanager is set as a suggestion in composer.json. I guess it should be a requirement since the package does not run without it.

**Comment by weierophinney** [comment]
`ModuleManager` is required if you're using `Application`, but for other uses cases (e.g., using only the router, or only the controller subcomponent), it's not required. This is why it has been marked as an optional dependency.
