### ISSUE TITLE
match all the routes starting with a given fragment

### ISSUE THREAD

**Issue by marcosh** [zendframework/zend-mvc#49]
I need to build a route matching anything starting with a given segment.

To be clear, I would like to match anything starting with `/foo`, so `/foo`, `foo/bar`, `foo/baz`, `foo/bar/baz`, ...

I could do it using a `Wildcard` router, but the documentation states it is deprecated and that I should use `Segment` instead.

Is there a way to do this using `Segment` or must I use `Regex` router?

On the other hand, is the `Wildcard` router planned to be removed from the future versions of the framework or is it going to stay? If it is going to stay I'd suggest to replace the `deprecated` annotation with something like `security issues` instead

**Comment by weierophinney** [comment]
It has not yet been removed, but we clearly note it in the documentation as both deprecated and a security issue:
- http://zendframework.github.io/zend-router/routing/#zend92mvc92router92http92wildcard-deprecated

If you want to match _anything_ following, I'd do so as a `Regex` route:

``` php
'regex' => '/foo(?P<path>/.*)$'
```

which will then capture any path segments after `/foo` as a single string under the route parameter "path".

@marcosh Can you please open an issue on [zend-router](https://github.com/zendframework/zend-router/issues) to request that we mark the wildcard and query routes with `@deprecated` annotations? (I don't know of any formal ones for security, but we can mention the security issues in the description of the annotations.) Thanks!
