### ISSUE TITLE
500 Internal Server error if request payload is empty and request content-type is application/json

### ISSUE THREAD

**Issue by kabirbaidhya** [zendframework/zend-mvc#50]
After a recent `composer update`, the application throws `Zend\Json\Exception\RuntimeException` on requests with no payload and along with content-type 'application/json'. 

Actually, in our application the default `Content-Type` is `'application/json'` so all the requests are sent along with this header. Thus, in case of requests with no payload, for instance `DELETE` request, the application throws this exception. As it is triggering `Zend\Json\Json::decode()` with empty value. 

Here's a part of stack trace for more info: 

```
Zend\Json\Exception\RuntimeException

File:
/var/www/cummings/vendor/zendframework/zend-json/src/Json.php:68
Message:
Decoding failed: Syntax error
Stack trace:
#0 /var/www/cummings/vendor/zendframework/zend-mvc/src/Controller/AbstractRestfulController.php(576): Zend\Json\Json::decode('', 1) #1 /var/www/cummings/vendor/zendframework/zend-mvc/src/Controller/AbstractRestfulController.php(350): Zend\Mvc\Controller\AbstractRestfulController->processBodyContent(Object(Zend\Http\PhpEnvironment\Request)) 
...
```

**Comment by svycka** [comment]
@kabirbaidhya duplicate https://github.com/zendframework/zend-mvc/issues/100
