### ISSUE TITLE
EventManager confusion

### ISSUE THREAD

**Issue by tklever** [zendframework/zend-mvc#51]
When I add this code to a fresh ZendSkeletonApplication in the Application Module.php

``` php
public function onBootstrap(MvcEvent $e)
{
    $eventManager = $e->getApplication()->getEventManager();

    $sm = $e->getApplication()->getServiceManager();
    $em = $sm->get('EventManager');

    var_dump($eventManager === $em, md5(spl_object_hash($eventManager)), md5(spl_object_hash($em)));
    exit;
}
```

I get this output

``` bash
TIM-KLEVER:ZendSkeletonApplication tklever$ php public/index.php 
bool(false)
string(32) "54d2698ecbf9ae3c0b05842f5dbd4fc5"
string(32) "0936bc105f2c2536b4e4f9159999cdda"
```

Shouldn't these event managers be the same?
Or if they are not, is there a reason why they aren't?

**Comment by weierophinney** [comment]
They are not supposed to be the same; please read the tutorial and
component documentation for the event manager to see the various use cases,
which also illustrate went they are different instances.

You can use the SharedEventManager instance to share listeners between
discrete EM instances.

**Comment by tklever** [comment]
Thanks for the clarification.

This line https://github.com/zendframework/zend-mvc/blob/master/src/Application.php#L111

``` php
$this->setEventManager($serviceManager->get('EventManager'));
```

made me think there were supposed to be the same instance.

**Comment by weierophinney** [comment]
Pulling it from the SM ensures that the instance has the shared manager
injected. The EM is marked in the SM as unshared (i.e., returns discrete
instances), while the shared manager is, well, shared. The EM factory
injected the shared manager in each instance it creates.

**Comment by tklever** [comment]
Found it in the docs

http://framework.zend.com/manual/current/en/modules/zend.mvc.services.html#servicemanager

Honestly, I'm shocked I didn't know that EM is not shared by default. How I didn't run into this revelation sooner is beyond me. Thanks again.
