### ISSUE TITLE
Suggestion for ZF3: extract FlashMessenger from Zend\Mvc for better reusability

### ISSUE THREAD

**Issue by RalfEggert** [zendframework/zend-mvc#52]
I would like to suggest to extract the `FlashMessenger` from the `Zend\Mvc` package for better reusability. Current scenario I am working on: I want to use something like that within an `Zend\Expressive` application.

**Comment by xtreamwayz** [comment]
Something like this?

https://github.com/slimphp/Slim-Flash

**Comment by gianarb** [comment]
Good for me.. But maybe a single component with this feature is to much stupid.. :)
In your opinion how it could grow?

**Comment by weierophinney** [comment]
Done - it's in [zend-mvc-plugin-flashmessenger](https://zendframework.github.io/zend-mvc-plugin-flashmessenger).
