### ISSUE TITLE
Hops not working properly

### ISSUE THREAD

**Issue by riznmage** [zendframework/zend-mvc#8]
Calling `$this->flashMessenger()->addMessage("Message text", "namespace", 2)` does not work as desired. It seems that the method `getMessagesFromContainer()` in `vendor/zendframework/zend-mvc/src/Controller/Plugin/FlashMessenger.php` unsets all namespaces, but it shouldn't do so.

**Comment by weierophinney** [comment]
> does not work as desired

Can you explain:
- What is the behavior _you_ expect?
- What are you actually observing?

**Comment by riznmage** [comment]
I've created a pull request. https://github.com/zendframework/zend-mvc/pull/9
