### ISSUE TITLE
BC broken for AbstractPluginManagerFactory

### ISSUE THREAD

**Issue by bacinsky** [zendframework/zend-mvc#85]
Excuse me, but 

changing this: https://github.com/zendframework/zend-mvc/blob/release-2.6.3/src/Service/AbstractPluginManagerFactory.php#L32
to this: https://github.com/zendframework/zend-mvc/blob/release-2.7.0/src/Service/AbstractPluginManagerFactory.php#L36
is a violation of backward compatibility.

My projects suddenly screams: Argument 1 passed to FooBarHelperPluginManager::__construct() must implement interface Zend\ServiceManager\ConfigInterface, instance of Zend\ServiceManager\ServiceManager given...

Thank you.

**Comment by weierophinney** [comment]
@bacinsky zend-mvc 2.7 now pins to zend-servicemanager `^2.7.5 || ^3.0.3`. The 2.7 series of zend-servicemanager updates the constructor of the `AbstractPluginManager` to allow both backwards compatibility with previous versions, as well as forwards-compatibility with the 3.0 series.

In the 2.X series, the first (and only) argument accepted to the constructor was a `Zend\ServiceManager\Config` instance, and this argument was nullable. In the 3.X series, the arguments are a parent container, and an array of configuration.

Based on the error you're getting, it sounds like you're providing an alternate constructor in your custom plugin manager, and it's calling on the parent constructor. As such, you'll want to update your constructor to follow that in the zend-servicemanager 2.7 series to ensure it's forwards compatible, _if you want to use it in conjunction with `Zend\Mvc\Service\AbstractPluginManagerFactory`_. Alternately, create a custom factory for your plugin manager instead.

**Comment by zluiten** [comment]
Small bc break, I had this problem as well.
