### ISSUE TITLE
BC broken for ServiceListenerFactory

### ISSUE THREAD

**Issue by bacinsky** [zendframework/zend-mvc#86]
Removed DependencyInjection:
https://github.com/zendframework/zend-mvc/blob/release-2.6.3/src/Service/ServiceListenerFactory.php#L88
https://github.com/zendframework/zend-mvc/blob/release-2.6.3/src/Service/ServiceListenerFactory.php#L52
is a BC violation:
https://github.com/zendframework/zend-mvc/blob/release-2.7.0/src/Service/ServiceListenerFactory.php

I'm not offending but this is just horrible, making my programmers hard life even harder, another two hours of my life wasted on useless finding of ZF2 BC issues. Isn't it possible to catch these bugs before they make to master?

**Comment by weierophinney** [comment]
@bacinsky —

> I'm not offending

Yes, actually, you are.

We are trying _very_ hard to avoid BC breaks. However, with so many moving parts, and an inability to test every single possible combination of components, this is often quite difficult. Our automated tests catch a ton, and as we make changes, no change is merged if a test is failing. But there's inevitably some breakage.

Please _assume that we are trying our best_, and then _respectfully_ point out where a break occurs, and, if possible, provide a test and/or a patch that will correct it. Yelling at the contributors for:

> making my programmers hard life even harder, another two hours of my life wasted

is not helping anyone. Nobody is trying to break things; accidents happen. Approach contributors with respect, and with a willingness to help.

**Comment by bacinsky** [comment]
@weierophinney Thank you for a nice comment, I agree that my report is not respectable and professional at all. I was under emotional pressure and it's like it is. I'm sorry and thank you for your hard work.
