### ISSUE TITLE
[2.7.1] Zend\Mvc\Controller\Plugin\Forward

### ISSUE THREAD

**Issue by ddetyuk** [zendframework/zend-mvc#90]
Zend\Mvc\Controller\Plugin\Forward do not detach Zend\Mvc\View\Http\InjectViewModelListener listener

https://github.com/zendframework/zend-mvc/blob/master/src/Controller/Plugin/Forward.php#L195-L196

sould be

``` php
    $callbacks = $currentCallback->getCallback();
    if ($callbacks[0] instanceof $class) {
        $sharedEvents->detach($id, $currentCallback);
```

instead of

``` php
    if ($currentCallback instanceof $class) {
        $sharedEvents->detach($currentEvent, $id);
```

**Comment by weierophinney** [comment]
Referenced the wrong issue in a commit I pushed; re-opening.
