### ISSUE TITLE
[2.7.1] composer.json missing  dependency on zend-serializer

### ISSUE THREAD

**Issue by steverhoades** [zendframework/zend-mvc#91]
Zend\Mvc\Service\SerializerAdapterPluginManagerFactory explicity uses Zend\Serializer\AdapterPluginManager.  Thus, if installing zend-mvc without the full framework this results in the following error:

```
Fatal error: Uncaught Error: Class 'Zend\Serializer\AdapterPluginManager' not found in /var/www/<myapp>/vendor/zendframework/zend-mvc/src/Service/AbstractPluginManagerFactory.php on line 36
```

After inspecting the composer.json file it has zend-serializer listed as a require-dev dependency.

**Comment by steverhoades** [comment]
It looks like this may affect almost everything listed in the require-dev dependency list actually.

**Comment by weierophinney** [comment]
This is actually on purpose. Most services that have factories should be
considered opt-in: if you don't need to use the service, there's no reason
to install the dependency. However, to make that explicit, our plan for the
v3 release is to move those factories to the respective components (with
some automation magic via composer for wiring them into the application).
