### ISSUE TITLE
using middleware in 'dispatch' event?

### ISSUE THREAD

**Issue by samsonasik** [zendframework/zend-mvc#92]
is it possible to use it in a 'dispatch' event, tried something like this:

``` php
$eventManager->attach('dispatch', $sm->get('AuthorizationMiddleware'));
```

and got the following error:

```
: Missing argument 2 for Application\Middleware\AuthorizationMiddleware::__invoke() in /Application/Middleware/AuthorizationMiddleware.php on line 7
```

While the error is argument 2, the argument 1 is an `MvcEvent` instance.

**Comment by weierophinney** [comment]
No, because they accept completely different arguments!

Event listeners receive an event instance, while middleware accepts a request, response, and optionally "next" callable. On top of that, the request and response from the MvcEvent are the zend-http types.

You could certainly wrap the middleware to make this happen:

``` php
use Zend\Psr7Bridge\Psr7Request;
use Zend\Psr7Bridge\Psr7Response;

$events->attach('dispatch', function ($e) use ($services) {
    $request = Psr7Request::fromZend($e->getRequest());
    $response = Psr7Response::fromZend($e->getResponse());
    $result = ($services->get('AuthorizationMiddleware'))($request, $response);
    // determine if a response should be returned, etc.
});
```

**Comment by samsonasik** [comment]
Thank you... I think it need to be documented ;)

Warm regards,

Abdul Malik Ikhsan

Pada 7 Mar 2016, pukul 23.41, weierophinney notifications@github.com menulis:

**Comment by weierophinney** [comment]
Why? The MiddlewareListener details its scope clearly already, and that scope does not include arbitrary event listeners... If you'd like to contribute a cookbook recipe, however, feel free to send a pull request. :wink:

**Comment by samsonasik** [comment]
@weierophinney here we go https://github.com/zendframework/zend-mvc/pull/94 for the PR doc ;)

**Comment by samsonasik** [comment]
closing in favor of #94
